### ISSUE TITLE
Madoko

### ISSUE THREAD

**Issue by jrappen** [mundimark/awesome-markdown-alternatives#1]
I found `madoko`:

* available via npm
* <https://www.madoko.net> (main site)
  * <https://www.madoko.net/editor.html> (online editor, works offline once loaded, export to PDF or HTML, work with Dropbox or Github files)
* <https://hg.codeplex.com/madoko> (code)
 * <https://github.com/koka-lang/madoko> (docs)
    * <https://github.com/koka-lang/madoko/blob/gh-pages/reference.pdf>
    * <https://www.microsoft.com/en-us/research/video/madoko-a-scholarly-markdown>

You can:

* output static HTML
* output PDF
* include files
* style code in code blocks

**Comment by geraldb** [comment]
@jrappen Great find. I'd say Madoko is a markdown dialect / variant / extension. You're more than welcome to add Madoko to the awesome-markdown page. Cheers.

**Comment by DonaldTsang** [comment]
@geraldb please defer people to https://github.com/babelmark/babelmark-registry in case they are talking about MD dialects
