### ISSUE TITLE
add rmarkdown in  awesome-markdown-alternatives is allow?

### ISSUE THREAD

**Issue by nkot56297** [mundimark/awesome-markdown-alternatives#3]
@geraldb Hi! How are you?

1. Apparently [rmarkdown](https://rmarkdown.rstudio.com/) is a dialect in markdown, can I add it as an alternative?
2. If allowed, I'll send the pull request today.
3. I await your reply.

**Comment by geraldb** [comment]
rmarkdown is more a markdown dialect / variant,  This page is for "true" alternatives.
