### ISSUE TITLE
Markdown alternatives

### ISSUE THREAD

**Issue by ghost** [mundimark/awesome-markdown-alternatives#4]
Hi @geraldb ! How are you?

I would like to add these Markdown alternatives in repository: [awesome-markdown-alternatives](https://github.com/mundimark/awesome-markdown-alternatives): 
1. [Rmarkdown](https://rmarkdown.rstudio.com/): Markdown dialect. 
2. [scroll](https://github.com/publicdomaincompany/scroll): Extensible alternative to Markdown. 
3. [unidok](https://github.com/Aloso/unidok): Powerful Asciidoctor alternative with Markdown syntax.
4. [Raylib_DrawTextStyle](https://github.com/NightenDushi/Raylib_DrawTextStyle): An alternative DrawText function with basic Markdown and custom line spacing.
5. [ssmd](https://github.com/machisuji/ssmd): Speech Synthesis Markdown (SSMD) is a lightweight alternative syntax for SSML.
6. [johndown](https://github.com/jcinnamond/johndown): A Markdown alternative.
7. [jot](https://github.com/shbhrsaha/jot): An alternative Markdown language specially-designed for intuitive, efficient note-taking.
8. [alt](https://github.com/qeaml/alt): Markdown alternative.
9. [strawdown](https://github.com/LastCleanShirt/strawdown): Straw Down Markdown Alternative.
10. [markzwei](https://github.com/seiferson/markzwei): A Markdown alternative.
11. [.bullet](https://github.com/cameronblandford/.bullet): A Markdown alternative designed for bullet journaling.
12. [SR-Markup-Lang](https://github.com/BluFedora/SR-Markup-Lang): An alternative to Markdown for my blogging needs.
13. [Remark](https://github.com/BradSharp/Remark): A simple backwards-compatible alternative to Markdown.

#### Notes
1. Hope to help.
2. Can I submit an pull request - with Markdown alternatives?

**Comment by geraldb** [comment]
I added a [MORE.md](https://github.com/mundimark/awesome-markdown-alternatives/blob/master/MORE.md) page for you - you are welcome to add your alternatives to the page.  Cheers. Prost.

**Comment by ghost** [comment]
Thank you @geraldb
